spring:
  application:
    name: oauth2-client
  security:
    oauth2:
      client:
        registration:

          spring:
            provider: "spring"
            client-id: "oidc-client"
            client-secret: "secret"
            authorization-grant-type: "authorization_code"
            client-authentication-method: "client_secret_basic"
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - "user.read"
              - "openid"

          webflux:
            provider: "spring"
            client-id: "webflux-client"
            client-secret: "msecret"
            authorization-grant-type: "authorization_code"
            client-authentication-method: "client_secret_basic"
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - "user.read"
              - "openid"

        provider:
          spring:
            issuer-uri: http://localhost:9000
